 server:
   servlet:
     context-path: /vendedor

 spring:
   datasource:
     url: jdbc:mysql://localhost:3306/db_dados?useSSL=false&createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true&useUnicode=true
     username: root
     password: becksara123

   jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#   http://localhost:8080/vendedor/swagger-ui/index.html#/
      
# server:
#   servlet:
#     context-path: /vendedor
    
# spring:
#   datasource:
#     url: jdbc:h2:mem:demodb
#     username: sa
#     password: 
#     driverClassName: org.h2.Driver

#   h2:
#     console:
#       enabled: true
#       path: /h2-console